#!/usr/bin/env python3

import subprocess
import sys
import signal
import os
import atexit
from urllib.parse import urlparse

if len(sys.argv) != 3:
    sys.exit(1)

def kill_on_port(port: str):
    p1childPids = subprocess.check_output(["lsof", "-ti", ":{0}".format(port)]).splitlines()
    if p1childPids != []:
            os.kill(int(p1childPids[0]), signal.SIGTERM)

cookiefn = sys.argv[1]
addr = sys.argv[2]
netloc = urlparse(addr).netloc
port = "10001"

atexit.register(kill_on_port, port)

serv = 'localhost:{0}'.format(port)
config = '[service]\nclient = yes\naccept = {0}\nconnect = {1}:443\n'.format(serv, netloc)

p1 = subprocess.Popen(["stunnel", "-fd", "0"], stdin=subprocess.PIPE)
p1.communicate(input=config.encode('utf-8'))

try:
    subprocess.run(["./testhttp_raw", serv, cookiefn, addr])
except FileNotFoundError:
    print("file \"testhttp_raw\" can not be found")
